### ISSUE TITLE
alternate names possible?

### ISSUE THREAD

**Issue by jersam** [llekn/openssl-ca#1]
Is is possible to use alternate names?

I run my own CA for internal projects, recently having a problem with root.dev and www.root.dev ssl mismatch issues.

curl: (51) SSL: certificate subject name 'www.root.dev' does not match target host name 'root.dev'

**Comment by llekn** [comment]
Hi @jersam ,

Sorry for the very long delay. If you are still interested I've updated the `openssl.conf` to add `www.` to app_name, and now certs generated should match `www.root.dev` as you asked.

Could you please confirm if this works for you?

**Comment by jersam** [comment]
pulling!

**Comment by jersam** [comment]
@llekn looks like that is working now!

**Comment by llekn** [comment]
Great! I'm going to close this then
