### ISSUE TITLE
v1 vs v3?

### ISSUE THREAD

**Issue by jersam** [llekn/openssl-ca#2]
Couple users have updated their chrome to 59.x on OSx and are getting ssl errors.

> ERR_SSL_SERVER_CERT_BAD_FORMAT

https://bugs.chromium.org/p/chromium/issues/detail?id=715969

Looking at the openssl.conf I am not sure what to edit to get to v3 certs...

**Comment by jersam** [comment]
Since chrome 59* hit the shelves I've been having issues with this one. Any idea for a fix on your end?

**Comment by llekn** [comment]
Hi @jersam I'm sorry about the delay, I just had now the time to look on this.

Apparently there was a missing `-extensions` param while creating the CSR and certificate, so v3 extensions were not added to the resultant cert (despite being specified on the `openssl.cnf` file! Welcome to OpenSSL hell)

I've just pushed to branch `v3-fix` a commit that should solve your problem. Could you pull this branch and confirm that now certs are working con Chrome 56+ ?

**Comment by jersam** [comment]
Awesome!

I'll give it a try on Monday

Thank you!

**Comment by jersam** [comment]
if i have a.dev which needs to 'renew' after pulling the branch, how do I go about 'renewals' haha....

**Comment by llekn** [comment]
You will have to update the index manually as currently there is no automated way about how to overwrite already issued certificates. To update the index and reissue certificates:

 - Open `./index.txt` and remove the lines of those certificates you want to reissue
 - Run `create_crt.sh` to create a new key, CSR and certificate (or run `create_csr.sh` and `sign_csr.sh` if you do not want to create a new key

This should overwrite the certificates (and or CSR/key) files on the `./out` folder

Let me know if I can help to test this.

**Comment by jersam** [comment]
Looks to be the fix

thanks!!!

**Comment by llekn** [comment]
@jersam great!

Merged in #3
